id: P006720
initial_creation_type: ocr
source_metadata:
  id: bdr:W27886
  title: རྣམ་དག་བདེ་བ་ཅན་གྱི་ཞིང་སྒྲུབ་པདྨ་འི་དྲྭ་བ
  author: ''
  volumes:
    3187c8a20ce14386a2850070a55a99f5:
      image_group_id: I4685
      title: ''
      volume_number: 1
      total_pages: 260
